language: php

sudo: false

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

git:
  depth: 3

before_install:
  - pecl install ds

install:
  - if [[ "$DEPENDENCIES" = "high" ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
  - if [[ "$DEPENDENCIES" = "low" ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

before_script:
  - phpenv config-rm xdebug.ini

script:
  - cp .env.test .env
  - phpunit
  - bin/phpcheck

cache:
  directories:
    - $HOME/.cache/composer/files
    - $HOME/.composer/cache/files
